name: Debug

on:
  push:
  workflow_dispatch:

env:
  COTOWALI_HASH: "${{ github.sha }}"

jobs:
  debug-linux:
    runs-on: ubuntu-latest
    env:
      VFLAGS: "-cc ${{ matrix.cc }}"
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
        timeout-minutes: 15
  debug-macos:
    runs-on: macos-latest
    env:
      VFLAGS: "-cc clang"
      # https://github.com/vlang/v/blob/525791fa3a4643ae9b04570f4b18056816bfda96/.github/workflows/ci.yml#L263
      PKG_CONFIG_PATH: /usr/local/opt/openssl@3/lib/pkgconfig
    steps:
      - uses: zakuro9715/setup-z@main
      - uses: actions/checkout@v2
      - run: z ci setup-v
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
        timeout-minutes: 15
